UNIFIED_RESEARCH_LIFECYCLE_VERSION="2026-10-06-v1"
PHASE_CONTRACT=("INFRASTRUCTURE","MARKET_HISTORY_SYNC","HISTORICAL_STRATEGY_RESEARCH",
                "HISTORICAL_SCIENCE_BOOTSTRAP","GRID_IMPORT","LIVE_LEARNING","PAPER_TRADING")
